---
- hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - vars/auth.yml
  roles:
    - { role: vmhost, qtask: facts }
    - { role: vmhost, qtask: powermgmt, when: broken is not defined }
