---
- hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - vars/auth.yml
    - vars/nfs_datastores.yml
  roles:
    - { role: datastore, qtask: facts }
    - { role: nfs, qtask: exports }
    - { role: datastore, qtask: mount }
