- set_fact:
    auth: &auth
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: false

- name: Gather info about ESXI host
  community.vmware.vmware_host_facts:
    <<: *auth
  delegate_to: localhost
  register: host_facts

- name: Show info about disks
  ansible.builtin.debug:
    var: hosts_facts.ansible_facts_.ansible_datastore
