- set_fact:
    auth: &auth
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: false

- name: Collect information about our connection
  community.vmware.vmware_about_info:
    <<: *auth
  register: connection_info
  delegate_to: localhost

- name: Display collected data
  ansible.builtin.debug:
    var: connection_info

- name: Collect VMHost facts
  community.vmware.vmware_host_facts:
    <<: *auth
  register: host_facts
  delegate_to: localhost

- name: Display collected data
  ansible.builtin.debug:
    var: host_facts
